INSERT INTO city (id, name, state_or_ut) VALUES
    (1, 'Mumbai', 'Maharashtra'),
    (2, 'Delhi', 'NCT of Delhi'),
    (3, 'Kolkata', 'West Bengal'),
    (4, 'Chennai', 'Tamil Nadu'),
    (5, 'Bengaluru', 'Karnataka'),
    (6, 'Hyderabad', 'Telangana'),
    (7, 'Ahmedabad', 'Gujarat'),
    (8, 'Pune', 'Maharashtra'),
    (9, 'Surat', 'Gujarat'),
    (10, 'Jaipur', 'Rajasthan'),
    (11, 'Kanpur', 'Uttar Pradesh'),
    (12, 'Lucknow', 'Uttar Pradesh'),
    (13, 'Nagpur', 'Maharashtra'),
    (14, 'Ghaziabad', 'Uttar Pradesh'),
    (15, 'Indore', 'Madhya Pradesh'),
    (16, 'Coimbatore', 'Tamil Nadu'),
    (17, 'Kochi', 'Kerala'),
    (18, 'Patna', 'Bihar'),
    (19, 'Kozhikode', 'Kerala'),
    (20, 'Bhopal', 'Madhya Pradesh'),
    (21, 'Thrissur', 'Kerala'),
    (22, 'Vadodara', 'Gujarat'),
    (23, 'Agra', 'Uttar Pradesh'),
    (24, 'Visakhapatnam', 'Andhra Pradesh'),
    (25, 'Malappuram', 'Kerala'),
    (26, 'Thiruvananthapuram', 'Kerala'),
    (27, 'Kannur', 'Kerala'),
    (28, 'Ludhiana', 'Punjab'),
    (29, 'Nashik', 'Maharashtra'),
    (30, 'Vijayawada', 'Andhra Pradesh'),
    (31, 'Madurai', 'Tamil Nadu'),
    (32, 'Varanasi', 'Uttar Pradesh'),
    (33, 'Meerut', 'Uttar Pradesh'),
    (34, 'Faridabad', 'Haryana'),
    (35, 'Rajkot', 'Gujarat'),
    (36, 'Jamshedpur', 'Jharkhand'),
    (37, 'Srinagar', 'Jammu and Kashmir'),
    (38, 'Jabalpur', 'Madhya Pradesh'),
    (39, 'Asansol', 'West Bengal'),
    (40, 'Vasai–Virar', 'Maharashtra'),
    (41, 'Prayagraj', 'Uttar Pradesh'),
    (42, 'Dhanbad', 'Jharkhand'),
    (43, 'Chhatrapati Sambhajinagar', 'Maharashtra'),
    (44, 'Amritsar', 'Punjab'),
    (45, 'Jodhpur', 'Rajasthan'),
    (46, 'Ranchi', 'Jharkhand'),
    (47, 'Raipur', 'Chhattisgarh'),
    (48, 'Kollam', 'Kerala'),
    (49, 'Gwalior', 'Madhya Pradesh'),
    (50, 'Durg–Bhilai', 'Chhattisgarh');
